[package]
name = "ge4g-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schemars = "0.8"
ge4g-core = { path = "../ge4g-core" }
ge4g-project = { path = "../ge4g-project" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3.15"
mlua = { version = "0.11", features = ["lua54", "vendored", "serialize"] }

[dev-dependencies]
ge4g-render2d = { path = "../ge4g-render2d" }
